name: quickly
description: Quickly is build for faster and cleaner development. It provides lots of extension methods on Widget, String, List and Map.
version: 5.4.0
homepage: "https://github.com/Aniketkhote/Quickly"

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
