name: quickly
description: Quickly is awesome flutter package for rapid development.
version: 1.1.0
homepage: "https://github.com/Aniketkhote/Quickly"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter: null