name: quickly
description: Quickly is build for faster and cleaner development. It provides lots of extension methods on Widget, String, List and Map.
version: 3.3.0
homepage: "https://github.com/Aniketkhote/Quickly"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
