name: quicker
description: Quicker is awesome flutter package to rapid development.
version: 0.0.1
homepage: "https://github.com/Aniketkhote/Quicker"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter: null